# Generated by Django 3.2.4 on 2022-04-18 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import randompinfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('pin', randompinfield.fields.RandomPinField(length=6)),
                ('sent', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
