# Generated by Django 3.2.4 on 2022-04-18 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20220418_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsverification',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='smsverification',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='v1649469077/file/shop/3fb459e3449905545701b418e8220334_tn_jbplnr.png', upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='smsverification',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
