# Generated by Django 3.2.4 on 2022-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220418_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsverification',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='smsverification',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='smsverification',
            name='time_st',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('ORTHER', 'ORTHER')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('C', 'Customer'), ('S', 'Seller')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='xu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no_user_c5clxa', upload_to=''),
        ),
    ]
