# Generated by Django 3.2.4 on 2022-04-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_smsverification_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no_user_c5clxa', upload_to='profile/'),
        ),
    ]
