# Generated by Django 3.2.4 on 2022-04-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no_user_mn2igp', upload_to='profile/'),
        ),
    ]
