# Generated by Django 3.2.4 on 2022-04-21 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_username_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 4, 21, 2, 58, 54, 605260, tzinfo=utc), null=True),
        ),
    ]
