# Generated by Django 3.2.4 on 2022-04-21 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20220421_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 4, 21, 10, 7, 59, 527343), null=True),
        ),
    ]
