# Generated by Django 3.2.4 on 2022-04-23 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20220422_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 10, 28, 19, 957811), null=True),
        ),
    ]
