# Generated by Django 3.2.4 on 2022-04-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
