# Generated by Django 3.2.4 on 2022-04-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no_user_ypl5wh.png', upload_to='profile/'),
        ),
    ]
