# Generated by Django 3.2.4 on 2022-05-04 06:25

from django.db import migrations, models
import randompinfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyemail',
            name='token',
        ),
        migrations.RemoveField(
            model_name='verifyemail',
            name='user',
        ),
        migrations.AddField(
            model_name='verifyemail',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verifyemail',
            name='otp',
            field=randompinfield.fields.RandomPinField(length=6, null=True),
        ),
    ]
