# Generated by Django 3.2.4 on 2022-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20220504_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='count_notifi_unseen',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
