# Generated by Django 3.2.4 on 2022-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_with_shock_deal',
            name='items',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buy_with_shock_deal',
            name='variations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='items',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='variations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='promotion_combo',
            name='items',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_program',
            name='items',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_program',
            name='variations',
            field=models.TextField(null=True),
        ),
    ]
