# Generated by Django 3.2.4 on 2022-07-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20220716_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_with_shock_deal',
            old_name='byproduct',
            new_name='byproducts',
        ),
        migrations.RenameField(
            model_name='buy_with_shock_deal',
            old_name='main_product',
            new_name='main_products',
        ),
        migrations.RenameField(
            model_name='flash_sale',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='promotion_combo',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='shop_program',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='product',
            new_name='products',
        ),
    ]
