# Generated by Django 3.2.4 on 2022-07-18 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220713_1959'),
        ('discounts', '0004_buy_with_shock_deal_list_byproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion_combo',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shop_program',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shop_program',
            name='variations',
        ),
        migrations.CreateModel(
            name='Variationflashsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user_item_limit', models.IntegerField(default=0)),
                ('promotion_stock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=2)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flah_sale', to='discounts.flash_sale')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_flash_sale', to='shop.item')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_flash_sale', to='shop.variation')),
            ],
        ),
        migrations.CreateModel(
            name='Variationdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user_item_limit', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=2)),
                ('created', models.DateTimeField(auto_now=True)),
                ('deal_shock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_shock', to='discounts.buy_with_shock_deal')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deal', to='shop.item')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_deal', to='shop.variation')),
            ],
        ),
        migrations.CreateModel(
            name='Variation_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promotion_stock', models.IntegerField(default=0)),
                ('user_item_limit', models.IntegerField(default=0)),
                ('promotion_price_after_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_discount', to='shop.item')),
                ('shop_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_program', to='discounts.shop_program')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_discount', to='shop.variation')),
            ],
        ),
    ]
