# Generated by Django 3.2.4 on 2022-07-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20220718_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='items',
        ),
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='list_byproducts',
        ),
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='variations',
        ),
        migrations.RemoveField(
            model_name='flash_sale',
            name='items',
        ),
        migrations.RemoveField(
            model_name='flash_sale',
            name='variations',
        ),
    ]
