# Generated by Django 3.2.4 on 2022-07-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20220718_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation_discount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='variationdeal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='variationflashsale',
            name='status',
        ),
        migrations.AddField(
            model_name='buy_with_shock_deal',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop_program',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation_discount',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variationdeal',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variationflashsale',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
