# Generated by Django 3.2.4 on 2022-07-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20220718_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation_discount',
            name='number_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='variationdeal',
            name='number_order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='variationflashsale',
            name='number_order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
