# Generated by Django 3.2.4 on 2022-07-24 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0008_auto_20220723_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='user',
        ),
        migrations.CreateModel(
            name='Voucheruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.voucher')),
            ],
        ),
    ]
