# Generated by Django 3.2.4 on 2022-07-29 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0009_auto_20220724_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_order_value', models.FloatField()),
                ('maximum_discount', models.FloatField(null=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField(default=0, null=True)),
                ('percent', models.IntegerField(default=0, null=True)),
                ('discount_type', models.CharField(choices=[('1', 'Percent'), ('2', 'Money')], max_length=15)),
                ('type_award', models.CharField(max_length=15)),
                ('type_voucher', models.CharField(default='Offer', max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='code_number',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='minimum_order_value',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='type_voucher',
        ),
        migrations.CreateModel(
            name='Gammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.award')),
                ('shop_award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_award', to='discounts.shop_award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gammer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='shop_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.shop_award'),
        ),
    ]
