# Generated by Django 3.2.4 on 2022-07-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220730_0100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0010_auto_20220729_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower_offer',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='follower_offer',
            name='maximum_discount',
        ),
        migrations.RemoveField(
            model_name='follower_offer',
            name='user',
        ),
        migrations.AddField(
            model_name='follower_offer',
            name='maximun_discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='follower_offer',
            name='minimum_order_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('follow_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_offder', to='discounts.follower_offer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
