# Generated by Django 3.2.4 on 2022-07-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_auto_20220730_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='shop_award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_shop_award', to='discounts.shop_award'),
        ),
    ]
