# Generated by Django 3.2.4 on 2022-12-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0013_rename_maximun_discount_follower_offer_maximum_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_with_shock_deal',
            name='variations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='variations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='shop_program',
            name='variations',
            field=models.JSONField(null=True),
        ),
    ]
