# Generated by Django 3.2.4 on 2022-07-12 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_variation_item'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byproductcart',
            name='byproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_byproduct', to='shop.variation'),
        ),
        migrations.AlterField(
            model_name='byproductcart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_item', to='shop.item'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.item'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='shop.variation'),
        ),
        migrations.AlterField(
            model_name='whishitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whish_item', to='shop.item'),
        ),
        migrations.AlterField(
            model_name='whishitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whish_product', to='shop.variation'),
        ),
    ]
