# Generated by Django 3.2.4 on 2022-07-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220712_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Byproductcart',
        ),
    ]
