# Generated by Django 3.2.4 on 2022-07-18 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220713_1959'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0006_auto_20220718_0940'),
        ('carts', '0002_auto_20220712_0823'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='cartitem',
            name='byproduct',
            field=models.ManyToManyField(blank=True, to='discounts.Variationdeal'),
        ),
        
        
        
    ]
