# Generated by Django 3.2.4 on 2022-07-18 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220713_1959'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0003_auto_20220718_0949'),
    ]

    operations = [
        
    
    ]
