# Generated by Django 3.2.4 on 2022-07-15 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_auto_20220713_1959'),
        ('carts', '0003_auto_20220715_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Byproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_cart', to='carts.cartitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_item', to='shop.item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_product', to='shop.variation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
