# Generated by Django 3.2.4 on 2022-07-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20220718_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='byproduct',
        ),
    ]
