# Generated by Django 3.2.4 on 2022-07-23 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220713_1959'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0008_auto_20220723_1326'),
        ('carts', '0004_auto_20220718_1716'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='cartitem',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.shop_program'),
        ),
        
    ]
