# Generated by Django 3.2.4 on 2022-07-24 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_auto_20220713_1959'),
        ('carts', '0005_auto_20220723_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Byproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='byproduct',
        ),
        migrations.DeleteModel(
            name='Byproductcart',
        ),
        migrations.AddField(
            model_name='byproduct',
            name='cartitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_cart', to='carts.cartitem'),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_item', to='shop.item'),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byproduct_product', to='shop.variation'),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
