# Generated by Django 3.2.4 on 2022-07-24 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_auto_20220713_1959'),
        ('carts', '0005_auto_20220723_1334'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='cartitem',
            name='amount_byproducts',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='amount_main_products',
            field=models.FloatField(default=0, null=True),
        ),
    ]
