# Generated by Django 3.2.4 on 2022-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20220724_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amount_byproducts',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='amount_main_products',
            field=models.FloatField(default=0, null=True),
        ),
    ]
