# Generated by Django 3.2.4 on 2022-04-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_with_shock_deal',
            old_name='from_valid',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='buy_with_shock_deal',
            old_name='to_valid',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='flash_sale',
            old_name='from_valid',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='flash_sale',
            old_name='to_valid',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='follower_offer',
            old_name='from_valid',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='follower_offer',
            old_name='to_valid',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='promotion_combo',
            old_name='from_valid',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='promotion_combo',
            old_name='to_valid',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='shop_award',
            old_name='from_valid',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='shop_award',
            old_name='to_valid',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='shop_program',
            old_name='from_valid',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='shop_program',
            old_name='to_valid',
            new_name='valid_to',
        ),
    ]
