# Generated by Django 3.2.4 on 2022-04-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='flash_sale',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='flash_sale',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='follower_offer',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='follower_offer',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='promotion_combo',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='promotion_combo',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='shop_program',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='shop_program',
            name='valid_to',
        ),
    ]
