# Generated by Django 3.2.4 on 2022-04-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flash_sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='flash_sale',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='follower_offer',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='follower_offer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promotion_combo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promotion_combo',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop_program',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shop_program',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Buy_with_shock_deal',
        ),
        migrations.DeleteModel(
            name='Flash_sale',
        ),
        migrations.DeleteModel(
            name='Follower_offer',
        ),
        migrations.DeleteModel(
            name='Promotion_combo',
        ),
        migrations.DeleteModel(
            name='Shop_award',
        ),
        migrations.DeleteModel(
            name='Shop_program',
        ),
    ]
