# Generated by Django 3.2.4 on 2022-04-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion_combo',
            old_name='valid_from',
            new_name='from_valid',
        ),
        migrations.RenameField(
            model_name='promotion_combo',
            old_name='valid_to',
            new_name='to_valid',
        ),
        migrations.RenameField(
            model_name='shop_program',
            old_name='valid_from',
            new_name='from_valid',
        ),
        migrations.RenameField(
            model_name='shop_program',
            old_name='valid_to',
            new_name='to_valid',
        ),
    ]
