# Generated by Django 3.2.4 on 2022-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='vocher',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vocher',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
