# Generated by Django 3.2.4 on 2022-04-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20220414_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop_program',
        ),
    ]
