# Generated by Django 3.2.4 on 2022-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20220414_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_with_shock_deal',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='buy_with_shock_deal',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flash_sale',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='follower_offer',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='follower_offer',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='promotion_combo',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='promotion_combo',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop_award',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop_award',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
