# Generated by Django 3.2.4 on 2022-04-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20220414_1705'),
        ('discount', '0002_auto_20220414_1735'),
        ('discount', '0003_delete_shop_program'),
    ]

    operations = [
    ]
