# Generated by Django 3.2.4 on 2022-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20220414_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_program',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop_program',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
