# Generated by Django 3.2.4 on 2022-04-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20220414_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='buy_with_shock_deal',
            name='valid_to',
        ),
    ]
