# Generated by Django 3.2.4 on 2022-04-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_auto_20220414_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop_program',
        ),
    ]
