# Generated by Django 3.2.4 on 2022-04-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220414_2012'),
        ('discount', '0007_delete_shop_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flash_sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='follower_offer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promotion_combo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shop_award',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buy_with_shock_deal',
        ),
        migrations.DeleteModel(
            name='Flash_sale',
        ),
        migrations.DeleteModel(
            name='Follower_offer',
        ),
        migrations.DeleteModel(
            name='Promotion_combo',
        ),
        migrations.DeleteModel(
            name='Shop_award',
        ),
    ]
