# Generated by Django 3.2.4 on 2022-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='gim',
            field=models.BooleanField(default=False),
        ),
    ]
