# Generated by Django 3.2.4 on 2022-07-11 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shop_description_url'),
        ('checkout', '0002_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_thread_gim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='gim',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_order', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='message',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_product', to='shop.item'),
        ),
        migrations.CreateModel(
            name='Messagemedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/')),
                ('file_preview', models.FileField(null=True, upload_to='chat/')),
                ('duration', models.FloatField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_media', to='chat.message')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_seen', models.BooleanField(default=True)),
                ('ignore', models.BooleanField(default=True)),
                ('gim', models.BooleanField(default=False)),
                ('blocker', models.ManyToManyField(blank=True, related_name='blocker', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_thread', to='chat.thread')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
