# Generated by Django 3.2.4 on 2022-07-11 05:02

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220711_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(max_length=200,null=True,choices=[('1','Message'),('2','Image'),('3','Video'),('4',"Product"),('5',"Order")],default='1'),
        ),
    ]
