# Generated by Django 3.2.4 on 2022-07-11 05:07

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nickname',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(max_length=200,null=True,choices=[('1','Message'),('2','Image'),('3','Video'),('4',"Product"),('5',"Order")],default='1'),
        ),
    ]
