# Generated by Django 3.2.4 on 2022-07-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('1', 'Message'), ('2', 'Image'), ('3', 'Video'), ('4', 'Product'), ('5', 'Order')], default='1', max_length=200, null=True),
        ),
    ]
