# Generated by Django 3.2.4 on 2022-07-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_message_type'),
        ('chat', '0007_message_message_type'),
    ]

    operations = [
    ]
