# Generated by Django 3.2.4 on 2022-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_merge_20220711_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('1', 'Message'), ('2', 'Image'), ('3', 'Video'), ('4', 'Product'), ('5', 'Order')], default='1', max_length=200, null=True),
        ),
    ]
