# Generated by Django 3.2.4 on 2022-04-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_home',
            new_name='Image_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_home',
        ),
        migrations.AddField(
            model_name='category',
            name='image_category',
            field=models.ManyToManyField(blank=True, to='category.Image_category'),
        ),
    ]
