from django.urls import path
from . import views
from .views import (ShopratingAPI,ShopprofileAPIView, ListvoucherAPI,ListcomboAPI,
ListdealshockAPI,ListprogramAPI,ListflashsaleAPI,Listordershop,
Newvoucher,
DetailVoucher,
NewcomboAPI,
DetailComboAPI,
NewDeal,
DetailDeal,
NewprogramAPI,
Detailprogram,
Newflashsale,
DetailFlashsale,
Dashboardpromotion
)
urlpatterns = [
    
    path("infoseller", views.infoseller),
    path("product/", views.product,name='product'),
    path("shop/rating",ShopratingAPI.as_view()),
    path("vouchers/list", ListvoucherAPI.as_view()),
    path("bundle/list", ListcomboAPI.as_view()),
    path("add-on-deal/list", ListdealshockAPI.as_view()),
    path("list/discount", ListprogramAPI.as_view()),
    path("shop-flash-sale/list", ListflashsaleAPI.as_view()),
    path("product/list", views.get_product,name='get_product'),
    path("product/<int:id>", views.update_item,name='update_item'),
    path("product/update_image", views.update_image,name='update_image'),
    path("product/category", views.add_item,name="add_item"),
    path("product/delete", views.delete_product,name="delete_product"),
    path("shipping/list", views.shipping,name="shipping"),
    path("shipping/shop/list", views.get_shipping),
    path("shop/create", views.create_shop,name="create_shop"),
    path("dashboard", views.my_dashboard,name="dashboard"),
    
    path('dashboard/promotion',Dashboardpromotion.as_view()),
    path('voucher/new',Newvoucher.as_view()),
    path('voucher/<int:id>',DetailVoucher.as_view()),
    path("follower-offer/create", views.follower_offer,name="follower_offer"),
    path("shop_award/create", views.shop_award,name="shop_award"),
    path("discount/create", NewprogramAPI.as_view()),
    path("discount/<int:id>",Detailprogram.as_view()),
    path("new_combo", NewcomboAPI.as_view()),
    path("combo/<int:id>", DetailComboAPI.as_view()),
    path("flashsale/create", Newflashsale.as_view()),
    path("flashsale/<int:id>", DetailFlashsale.as_view()),
    path("new_deal", NewDeal.as_view()),
    path('deal_shock/<int:id>',DetailDeal.as_view(),name="item_deal_shock"),
    path("home/seller", views.homeseller),
    path("shop/profile",ShopprofileAPIView.as_view()),
    path("shop/order",Listordershop.as_view()),
]