# Generated by Django 3.2.4 on 2022-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_searchkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkey',
            name='total_searches',
            field=models.IntegerField(default=0),
        ),
    ]
