# Generated by Django 3.2.4 on 2022-04-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_searchkey_total_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
