# Generated by Django 3.2.4 on 2022-04-28 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myweb', '0005_image_home_upload_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_home',
            name='upload_by',
        ),
        migrations.AddField(
            model_name='image_home',
            name='upload_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
