# Generated by Django 3.2.4 on 2022-04-14 05:12

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='', validators=[cloudinary_storage.validators.validate_video])),
                ('duration', models.IntegerField(null=True)),
                ('file_preview', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reson', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=200, null=True)),
                ('info_more', models.TextField(max_length=2000, null=True)),
                ('review_rating', models.IntegerField(null=True)),
                ('rating_product', models.IntegerField(null=True)),
                ('xu', models.IntegerField(null=True)),
                ('rating_seller_service', models.IntegerField(null=True)),
                ('rating_shipping_service', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('anonymous_review', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('like', models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL)),
                ('media_upload', models.ManyToManyField(blank=True, to='actionorder.Media_review')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
