# Generated by Django 3.2.4 on 2022-04-12 09:04

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_review',
            name='file',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
