# Generated by Django 3.2.4 on 2022-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
