# Generated by Django 3.2.4 on 2022-04-08 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_more_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_quantity', models.IntegerField()),
                ('to_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color/')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('quantity_limit', models.IntegerField(null=True)),
                ('quantity_limit_flash_sale', models.IntegerField(null=True)),
                ('sku_product', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('1', 'New'), ('2', 'Like New')], default='1', max_length=20)),
                ('pre_order', models.CharField(max_length=10, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('price_ship', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('buy_more_discount', models.ManyToManyField(blank=True, to='shop.Buy_more_discount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('liked', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('logo', models.ImageField(null=True, upload_to='shop/')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('shop_type', models.CharField(choices=[('Mall', 'Shopmall'), ('Favourite', 'Favourite')], max_length=25, null=True)),
                ('slug', models.SlugField(null=True)),
                ('image_cover', models.ImageField(null=True, upload_to='shop/')),
                ('user_type', models.CharField(blank=True, choices=[('C', 'Customer'), ('S', 'Seller')], max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('ORTHER', 'ORTHER')], max_length=10)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('xu', models.IntegerField(default=0, null=True)),
                ('is_online', models.DateTimeField(auto_now=True)),
                ('online', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('shipping', models.ManyToManyField(blank=True, to='shipping.Shipping')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
                ('view', models.ManyToManyField(blank=True, to='shop.IpModel')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('number_of_promotional_products', models.IntegerField(default=0)),
                ('percent_discount', models.IntegerField(default=0, null=True)),
                ('inventory', models.IntegerField()),
                ('sku_classify', models.CharField(max_length=20, null=True)),
                ('limited_product_bundles', models.IntegerField(null=True)),
                ('percent_discount_deal_shock', models.IntegerField(null=True)),
                ('percent_discount_flash_sale', models.IntegerField(null=True)),
                ('quantity_flash_sale_products', models.IntegerField(null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size')),
            ],
        ),
        migrations.CreateModel(
            name='UploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='item/')),
                ('image_preview', models.FileField(null=True, upload_to='item/')),
                ('duration', models.FloatField(null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='media_upload',
            field=models.ManyToManyField(blank=True, to='shop.UploadItem'),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_choice',
            field=models.ManyToManyField(blank=True, related_name='shipping_choice', to='shipping.Shipping'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='item',
            name='view',
            field=models.ManyToManyField(blank=True, to='shop.IpModel'),
        ),
        migrations.CreateModel(
            name='Byproductcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('byproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
