# Generated by Django 3.2.4 on 2022-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.AddField(
            model_name='shop',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('ORTHER', 'ORTHER')], max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_cover',
            field=models.ImageField(null=True, upload_to='shop/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_online',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='user_type',
            field=models.CharField(blank=True, choices=[('C', 'Customer'), ('S', 'Seller')], max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='xu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='zip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(null=True, upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
