# Generated by Django 3.2.4 on 2022-12-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail',
            field=models.JSONField(null=True),
        ),
    ]
