# Generated by Django 3.2.4 on 2022-04-12 08:58

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220412_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaditem',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='item/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
