# Generated by Django 3.2.4 on 2022-04-12 11:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_uploaditem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaditem',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='item/'),
        ),
    ]
