# Generated by Django 3.2.4 on 2022-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pre_order',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
