# Generated by Django 3.2.4 on 2022-04-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_item_pre_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['color']},
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
