# Generated by Django 3.2.4 on 2022-04-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220416_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='online',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='xu',
        ),
    ]
