# Generated by Django 3.2.4 on 2022-04-23 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220419_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='view',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='view',
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ShopViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_views', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_views', to='shop.item')),
            ],
        ),
    ]
