# Generated by Django 3.2.4 on 2022-04-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220423_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopviews',
            name='shop',
        ),
        migrations.DeleteModel(
            name='ProductViews',
        ),
        migrations.DeleteModel(
            name='ShopViews',
        ),
    ]
