# Generated by Django 3.2.4 on 2022-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_notify_read'),
        ('shop', '0015_itemviews_shopviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description_url',
            field=models.ManyToManyField(blank=True, to='myweb.Image_home'),
        ),
    ]
