# Generated by Django 3.2.4 on 2022-07-12 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shop_description_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_item', to='shop.item'),
        ),
    ]
