# Generated by Django 3.2.4 on 2022-07-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_variation_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyMoreDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_quantity', models.IntegerField()),
                ('to_quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='buy_more_discount',
        ),
        migrations.DeleteModel(
            name='Buy_more_discount',
        ),
        migrations.AddField(
            model_name='buymorediscount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buymore_item', to='shop.item'),
        ),
    ]
