# Generated by Django 3.2.4 on 2022-07-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220730_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity_limit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_limit_flash_sale',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='limited_product_bundles',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='number_of_promotional_products',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='percent_discount',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='percent_discount_deal_shock',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='percent_discount_flash_sale',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='quantity_flash_sale_products',
        ),
    ]
