# Generated by Django 3.2.4 on 2022-10-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220730_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='violet',
            field=models.BooleanField(default=False),
        ),
    ]
