# Generated by Django 3.2.4 on 2022-10-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20221027_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_upload',
            field=models.ManyToManyField(blank=True, related_name='media_upload', to='shop.UploadItem'),
        ),
    ]
