# Generated by Django 3.2.4 on 2022-12-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_item_media_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
    ]
