from django.urls import path
from . import views
from django.conf.urls import include
from .views import (
    ChangePasswordView,
    HomeAPIView,
    CategoryListView,
    ItemAPIView,
    DetailAPIView,
    ShopinfoAPIVIew,
    MessageAPIView,
    ThreadAPIView,
    ProfileAPIView,
    ImageHomeAPIView,
    ListItemRecommendAPIView,
    SetNewPasswordAPIView,
    PasswordResetView,
    ProductInfoAPIVIew,
    CartItemAPIView,
    UpdateCartAPIView,
    OrderinfoAPIView,
    AddToCardBatchAPIView,
    DealShockAPIView,
    PromotionAPIView,
    CheckoutAPIView,
    Category_home,
    CartAPIView,
    ListorderAPIView,
    AddToCartAPIView,
    SearchitemAPIView,
    PurchaseAPIView,
    AddressAPIView,
    UserView,
    Itemrecently,
    ListThreadAPIView,
    Sendotp,VerifySMSView,
    RegisterView, LoginView,  LogoutView 
)

urlpatterns = [
    
    path(
        "reset/password/", views.PasswordResetView.as_view(), name="rest_password_reset"
    ),
     path(
        'password-reset/<uidb64>/<token>/',
        views.SetNewPasswordAPIView.as_view(),
        name="password-reset-confirm",
    ),
    
    path('register', RegisterView.as_view()),
    path('login', LoginView.as_view()),
    path('category/home',Category_home.as_view()),
    path('update/image', views.update_image),
    path('item/recently',Itemrecently.asview()),
    path("verify-sms", views.VerifySMSView.as_view()),
    path("resend-sms", views.Sendotp.as_view()),
    path('logout', LogoutView.as_view()),
    path('user-id/', UserView.as_view()),
    path('change/password/', ChangePasswordView.as_view()),
    path('products', HomeAPIView.as_view()),
    path('product/recommend', ListItemRecommendAPIView.as_view()),
    path('imagehome', ImageHomeAPIView.as_view()),
    path('categories', CategoryListView.as_view()),
    path('product_recent', ItemAPIView.as_view()),
    path('add-to-cart', AddToCartAPIView.as_view()),
    path('cart', CartAPIView.as_view()),
    path('listorder',  ListorderAPIView.as_view()),
    path('order/<int:id>',  OrderinfoAPIView.as_view()),
    path('detail/<slug>',DetailAPIView.as_view()),
    path('shopinfo',ShopinfoAPIVIew.as_view()),
    path('productinfo',ProductInfoAPIVIew.as_view()),
    path('addon-deal-cart-selection/<int:id>', DealShockAPIView.as_view()),
    path('bundle-deal/<int:id>', PromotionAPIView.as_view()),
    path('add-to-cart-batch',AddToCardBatchAPIView.as_view()),
    path('message', MessageAPIView.as_view()),
    path('search', SearchitemAPIView.as_view()),
    path('chat', ThreadAPIView.as_view()),
    path('thread/list', ListThreadAPIView.as_view()),
    path('upload-file',views.upload_file),
    path('profile',ProfileAPIView.as_view()),
    path('purchase',PurchaseAPIView.as_view()),
    path('cartview',CartItemAPIView.as_view()),
    path('updatecart',UpdateCartAPIView.as_view()),
    path('checkout', CheckoutAPIView.as_view()),
    path('payment', views.payment_complete),
    path('save_voucher',views.save_voucher),
    path('update_address',AddressAPIView.as_view()),
    path('get_city',views.get_city),
    path('get_address',views.get_address),
    
]