from django.test import TestCase

# Create your tests here.
category1=[
    {"title":"Áo","choice":false},
    {"title":"Quần","choice":false},
    {"title":"Quần đùi","choice":false},
    {"title":"Váy","choice":true},
    {"title":"Quần jeans","choice":true},
    {"title":"Đầm","choice":true},
    {"title":"Váy cưới","choice":true},
    {"title":"Đồ liền thân","choice":false},
    {"title":"Áo khoác","choice":false},
    {"title":"Áo len","choice":true},
    {"title":"Hoodie và Áo nỉ","choice":false},
    {"title":"Bộ","choice":false},
    {"title":"Đồ lót","choice":false},
    {"title":"Đồ ngủ","choice":false},
    {"title":"Đồ Bầu","choice":false},
]
category2=[
    {"title":"Quần jeans","choice":true},
    {"title":"Áo","choice":false},
    {"title":"Quần dài","choice":false},
    {"title":"Quần đùi","choice":false},
    {"title":"Com lê","choice":false},
    {"title":"Trang phục ngành nghề","choice":true},
    {"title":"Trang phục truyền thống","choice":false},
    {"title":"Đồ liền thân","choice":false},
    {"title":"Áo khoác","choice":false},
    {"title":"Áo len","choice":true},
    {"title":"Hoodie và Áo nỉ","choice":false},
    {"title":"Bộ","choice":false},
    {"title":"Đồ lót","choice":false},
    {"title":"Đồ ngủ","choice":false},
    {"title":"Đồ hóa trang","choice":false},
    {"title":"Vớ/ Tất","choice":true},
]
category3=[
    {"title":"Chăm sóc tay, chân & móng","choice":true},
    {"title":"Áo","choice":false},
    {"title":"Chăm sóc tóc","choice":false},
    {"title":"Chăm sóc nam giới","choice":false},
    {"title":"Nước hoa","choice":false},
    {"title":"Trang phục ngành nghề","choice":true},
    {"title":"Trang phục truyền thống","choice":false},
    {"title":"Đồ liền thân","choice":false},
    {"title":"Áo khoác","choice":false},
    {"title":"Áo len","choice":true},
    {"title":"Hoodie và Áo nỉ","choice":false},
    {"title":"Bộ","choice":false},
    {"title":"Đồ lót","choice":false},
    {"title":"Đồ ngủ","choice":false},
    {"title":"Đồ hóa trang","choice":false},
    {"title":"Vớ/ Tất","choice":true},
]