# Generated by Django 3.2.4 on 2022-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20220712_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='count_message_unseen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_seen',
            field=models.BooleanField(default=True),
        ),
    ]
