# Generated by Django 3.2.4 on 2022-07-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20220712_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('1', 'Message'), ('2', 'Image'), ('3', 'Video'), ('4', 'Product'), ('5', 'Order'), ('6', 'Other')], default='1', max_length=200),
        ),
    ]
