# Generated by Django 3.2.4 on 2022-07-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_reportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='reason',
            field=models.CharField(default='Khác', max_length=100),
        ),
        migrations.CreateModel(
            name='Mediareport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.reportuser')),
            ],
        ),
    ]
