# Generated by Django 3.2.4 on 2022-07-12 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220712_0823'),
        ('orderactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='orderitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_item', to='carts.cartitem'),
        ),
    ]
