# Generated by Django 3.2.4 on 2022-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderactions', '0003_rename_orderitem_review_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_review',
            name='file_preview',
        ),
        migrations.AddField(
            model_name='media_review',
            name='media_preview',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
