# Generated by Django 3.2.4 on 2022-04-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='deal_shock',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='flash_sale',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='promotion_combo',
        ),
    ]
