# Generated by Django 3.2.4 on 2022-04-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_buy_with_shock_deal_flash_sale_follower_offer_promotion_combo_shop_award_shop_program'),
        ('cart', '0002_auto_20220414_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deal_shock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.buy_with_shock_deal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flash_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.flash_sale'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.promotion_combo'),
        ),
    ]
