# Generated by Django 3.2.4 on 2022-07-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220414_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
    ]
