# Generated by Django 3.2.4 on 2022-04-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_unit',
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_unit',
            field=models.ManyToManyField(to='shipping.Shipping_unit'),
        ),
    ]
