# Generated by Django 3.2.4 on 2022-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20220410_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='tax_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_unit',
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Shipping_unit',
        ),
    ]
