# Generated by Django 3.2.4 on 2022-07-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220712_0823'),
        ('orders', '0002_rename_vocher_order_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_cartitem', to='carts.CartItem'),
        ),
    ]
