# Generated by Django 3.2.4 on 2022-07-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220713_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_voucher',
            field=models.FloatField(default=0, null=True),
        ),
    ]
