# Generated by Django 3.2.4 on 2022-07-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount_voucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
