# Generated by Django 3.2.4 on 2022-07-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_auto_20220730_0100'),
        ('orders', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_voucher', to='discounts.award'),
        ),
        migrations.AddField(
            model_name='order',
            name='follower_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_voucher', to='discounts.follower_offer'),
        ),
    ]
