# Generated by Django 3.2.4 on 2022-07-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220730_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_offer',
            field=models.FloatField(default=0, null=True),
        ),
    ]
